version: '3'

services:
  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    restart: always
    ports:
      - "8500:8500"
    command: "consul agent -dev -client=0.0.0.0 -ui"
    networks:
      - myapp

  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "9999:9999"
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      - consul-server
    networks:
      - myapp
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500

  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8081:8081"
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy
    networks:
        - myapp
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
      - CONFIG_SERVICE_URL=http://config-service:9999

  inventory-service:
    build: ./inventory-service
    container_name:   inventory-service
    ports:
      - "8082:8082"
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - myapp
    environment:
      - CONSUL_HOST=consul-server
      - CONSUL_PORT=8500
      - CONFIG_SERVICE_URL=http://config-service:9999


networks:
  myapp: