version: '3'

services:
  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    restart: always
    ports:
      - "8500:8500"
    command: "consul agent -dev -client 0.0.0.0 -ui"
